name: tester-windows

on:
  workflow_run:
    workflows: [Build Windows artifacts]
    types:
      - completed
  
jobs:
  windows-e2e-ocp:
    uses: adrianriobo/crc/.github/workflows/windows-qe-tpl.yml@fix-4040-extended
    strategy:
      fail-fast: false
      matrix:
        qe-type: ['e2e','integration']
        preset: ['openshift', 'microshift', 'all']
        exclude:
        - qe-type: 'e2e'
          preset: 'all'
        - qe-type: 'integration'
          preset: ['openshift', 'microshift']
    with:
      workflow-id: ${{ github.event.workflow_run.workflow_id }}
      qe-type: ${{matrix.qe-type}}
      preset: ${{matrix.preset}}
    secrets:
      pull-secret: ${{secrets.PULL_SECRET}}
      arm-tenant-id: ${{secrets.ARM_TENANT_ID}}
      arm-subscription-id: ${{secrets.ARM_SUBSCRIPTION_ID}}
      arm-client-id: ${{secrets.ARM_CLIENT_ID}}
      arm-client-secret: ${{secrets.ARM_CLIENT_SECRET}}
