# The template is intended to be used from a workflow run 
# as it will pick the artifacts from the triger (through workflow_id param)
name: windows-qe-tpl

on:  
  workflow_call:  
    inputs:  
      trigger-workflow-run-id:  
        description: run-id of the workflow which originate the execution and where the artifacts have been built
        required: true  
        type: string
      qe-type:  
        description: type of test; allowed values e2e or integration
        required: true  
        type: string
      preset:
        description: preset type only required if qe-type is e2e
        type: string  

jobs:
  windows-qe:
    runs-on: ubuntu-latest
    permissions:
      statuses: write # needed to update commit status (pending/failure/sucess)
      checks: write # as documented in https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['11']
        windows-featurepack: ['23h2-ent']
      
    steps:
    - name: Download gh contexta
      id: download-gh-context-artifact
      uses: actions/download-artifact@v4
      with:
        name: gh-context
        run-id: ${{inputs.trigger-workflow-run-id}}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download windows installer
      id: download-windows-installer-artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-installer
        run-id: ${{inputs.trigger-workflow-run-id}}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Download qe oci image
      id: download-qe-oci-image-artifact
      uses: actions/download-artifact@v4
      with:
        name: crc-${{inputs.qe-type}}-windows-amd64
        run-id: ${{inputs.trigger-workflow-run-id}}
        github-token: ${{ secrets.GITHUB_TOKEN }}git 

    