name: tester-windows

on:
  workflow_run:
    workflows: [Build Windows artifacts]
    types:
      - completed
  
jobs:
  windows-e2e-ocp:
    uses: crc-org/crc/.github/workflows/windows-qe-tpl.yml@main
    strategy:
      fail-fast: false
      matrix:
        qe-type: ['e2e','integration']
        preset: ['openshift', 'microshift', 'all']
        exclude:
        - qe-type: 'e2e'
          preset: 'all'
        - qe-type: 'integration'
          preset: 'openshift'
        - qe-type: 'integration'
          preset: 'microshift'
    with:
      trigger-workflow-run-id: ${{ github.event.workflow_run.id }}
      qe-type: ${{matrix.qe-type}}
      preset: ${{matrix.preset}}
    secrets: inherit
    
